@mini.API_HostAddress = https://localhost:7005/api/products

###

GET {{mini.API_HostAddress}}/getAll
Accept: application/json

###

POST {{mini.API_HostAddress}}/create
Content-Type: application/json

{
  "name": "Test Product",
  "description": "This is a sample product description",
  "price": 99.99
}

###
GET {{mini.API_HostAddress}}/get/1
Accept: application/json

