// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mini.Infrastructure.Data;

#nullable disable

namespace mini.Infrastructure.Migrations
{
    [DbContext(typeof(SampleProductsDbContext))]
    [Migration("20260225113759_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("mini.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yüksek performanslı laptop",
                            Name = "Laptop",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gelişmiş özelliklere sahip akıllı telefon",
                            Name = "Akıllı Telefon",
                            Price = 800.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Taşınabilir ve güçlü tablet",
                            Name = "Tablet",
                            Price = 600.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
